name: Latest Posts

on:
  workflow_dispatch:
  schedule:
    - cron: 5 5 * * 1

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "6"
          feed_list: ${{ secrets.GH_WWW }}
          committer_email: ${{ secrets.GH_CM }}
          committer_username: ${{ secrets.GH_CA }}